Update Community Slack link 🚀
rladies/rladiesguide pull request #115
Opened 2023-11-15 00:03 UTC by rivaquiroga

The new sign-up form is ready, thanks to @averigg ✨ 
Once https://github.com/rladies/rladies.github.io/pull/258 is merged, the new link will be available and we can merge this PR to update our Guide.

2023-11-15 00:12 UTC, rivaquiroga commented
Closes #114
Closes #97

2023-11-15 13:30 UTC, rivaquiroga commented
Closes #102

2024-02-13 20:52 UTC, drmowinckels requested changes
Update form link

2024-02-13 20:52 UTC, drmowinckels commented on content/comm/directory/index.en.md
> +Thanks so much for adding your name to the R-Ladies Global directory! If you're interested and are not already a member, please feel free to join our R-Ladies Global Community Slack. You can sign up
```suggestion
Thanks so much for adding your name to the R-Ladies Global directory! 
If you're interested and are not already a member, please feel free to join our R-Ladies Global Community Slack. 
You can sign up using the [Community sign-up form](https://rladies.org/form/community-slack/). 
It's a fun and welcoming space to meet other members of R-Ladies Global, talk about how awesome R is, and ask R questions.
```

2024-02-13 20:52 UTC, drmowinckels commented on content/comm/slack/index.en.md
> +Go to the [sign-up link](https://rladies.org/community-slack-form).
```suggestion
Go to the [sign-up link](https://rladies.org/form/community-slack/).
```

2024-02-13 20:52 UTC, drmowinckels commented on content/comm/twitter/index.en.md
> +https://rladies.org/community-slack-form
```suggestion
https://rladies.org/form/community-slack/
```

2024-02-13 20:52 UTC, drmowinckels commented on content/coordination/monitoring/index.en.md
> +([https://rladies.org/community-slack-form](https://rladies.org/community-slack-form)),
```suggestion
([https://rladies.org/form/community-slack/](https://rladies.org/form/community-slack/)),
```

2024-02-13 20:52 UTC, drmowinckels commented on content/coordination/monitoring/index.en.md
> +([https://rladies.org/community-slack-form](https://rladies.org/community-slack-form)),
```suggestion
([https://rladies.org/form/community-slack/](https://rladies.org/form/community-slack/)),
```

2024-02-13 20:52 UTC, drmowinckels commented on content/coordination/onboarding/index.en.md
> +(https://rladies.org/community-slack-form) and start a
```suggestion
(https://rladies.org/form/community-slack/) and start a
```

2024-02-13 20:52 UTC, drmowinckels commented on content/organization/online-presence/slack/index.en.md
> +You might want to read the [phrasing used for the community slack](/comm/slack/), see also the form used for [sign up](https://rladies.org/community-slack-form)
```suggestion
You might want to read the [phrasing used for the community slack](/comm/slack/), see also the form used for [sign up](https://rladies.org/form/community-slack/)
```

2024-02-13 20:52 UTC, drmowinckels commented on content/rocur/about/index.en.md
> +This RoCur is managed by R-Ladies Global members. You can email us at `WeAre@rladies.org` or at the **#rocur_twitter** channel on the [R-Ladies Community Slack](https://rladies.org/community-slack-fo
```suggestion
This RoCur is managed by R-Ladies Global members. You can email us at `WeAre@rladies.org` or at the **#rocur_twitter** channel on the [R-Ladies Community Slack](https://rladies.org/form/community-slack/).  
```

2024-02-13 20:52 UTC, drmowinckels commented on content/rocur/admin guide/index.en.md
> +* The #rocur_twitter channel on the [R-Ladies Community Slack](https://rladies.org/community-slack-form).
```suggestion
* The #rocur_twitter channel on the [R-Ladies Community Slack](https://rladies.org/form/community-slack/).  
```

2024-02-24 20:24 UTC, merged