update youtube form location
rladies/rladiesguide pull request #94
Opened 2023-06-26 08:41 UTC by drmowinckels

2023-08-24 10:38 UTC, maelle requested changes
The link looks wrong?

2023-08-24 10:38 UTC, maelle commented on content/organization/events/youtube/index.en.md
> +Please [fill in this form](shrv1UVaYyoxsAvzU) to notify us about your channel, and we'll subscribe as soon as we can.
this is not a link?

2024-01-23 14:48 UTC, drmowinckels reviewed
update youtube form link. Ready when https://github.com/rladies/rladies.github.io/pull/272 is merged

2024-01-23 14:48 UTC, drmowinckels commented on content/organization/events/youtube/index.en.md
> +If you run an R-Ladies chapter and have a video of a meetup you want hosted on the Global channel, please [fill in this form](shrv1UVaYyoxsAvzU) and we wil get to you as soon as we can.
```suggestion
If you run an R-Ladies chapter and have a video of a meetup you want hosted on the Global channel, please [fill in this form](shrv1UVaYyoxsAvzU) and we wil get to you as soon as we can.  
```
```suggestion
If you run an R-Ladies chapter and have a video of a meetup you want hosted on the Global channel, please [fill in this form](https://rladies.org/form/youtube) and we wil get to you as soon as we can.  
```

2024-01-23 14:48 UTC, drmowinckels commented on content/organization/events/youtube/index.en.md
> +Please [fill in this form](shrv1UVaYyoxsAvzU) to notify us about a video you want added to a playlist (or make a new playlist), and we will get to it as soon as we can.
```suggestion
Please [fill in this form](https://rladies.org/form/youtube) to notify us about a video you want added to a playlist (or make a new playlist), and we will get to it as soon as we can.
```

2024-01-30 08:01 UTC, maelle approved these changes

2024-02-13 20:54 UTC, merged